IntegracaoPagador/Models/SaleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using AutoMapper;
using IntegracaoPagador.Models.Enums;

namespace IntegracaoPagador.Models
{
    public class SaleViewModel
    {
        public string MerchantOrderId { get; set; }
        [Required]
        [StringLength(255, ErrorMessage = "The Customer Name  value cannot exceed 255 characters.")]
        public string CustomerName { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The Payment type value cannot exceed 100 characters.")]
        public string PaymentType { get;  set; }
        [Required]
        public long PaymentAmount { get; set; }
        [Required]
        public virtual ProviderEnum PaymentProvider { get; set; }
        [Required]
        public int PaymentInstallments { get; set; }
        [Required]
        [StringLength(16, ErrorMessage = "The CreditCardCard Number value cannot exceed 16 characters.")]
        public string CreditCardCardNumber { get; set; }
        [Required]
        [StringLength(25, ErrorMessage = "The CreditCard Holder value cannot exceed 25 characters.")]
        public string CreditCardHolder { get; set; }
        [Required]
        [StringLength(7, ErrorMessage = "The CreditCard ExpirationDate value cannot exceed 7 characters.")]
        public string CreditCardExpirationDate { get; set; }
        [Required]
        [StringLength(4, ErrorMessage = "The CreditCard Security Code value cannot exceed 4 characters.")]
        public string CreditCardSecurityCode { get; set; }
        [Required]
        public BrandEnum CreditCardBrand { get; set; }
        [Required]
        public TypeSendEnum TypeSend { get; set; }

    }
}

IntegracaoPagador/Controllers/SaleController.cs
using System;
using System.Configuration;
using System.Text;
using System.Web.Mvc;
using IntegracaoPagador.Models;
using System.Threading.Tasks;
using IntegracaoPagador.Models.Enums;
using IntegracaoPagador.PagadorSoapSearch;
using IntegracaoPagador.Service;
using TransactionDataRequest = IntegracaoPagador.PagadorSoapSearch.TransactionDataRequest;

namespace IntegracaoPagador.Controllers
{
    public class SaleController : Controller
    {
        public readonly ISoapRequestService SoapRequestService;
        public readonly IRestRequestService RestRequestService;
        public readonly IRestSearchService SearchRestService;
        public readonly ISoapSearchService SearchSoapService;
        public readonly IRestSearchServiceWrapper RestSerchServiceWrapper;

        public SaleController(ISoapRequestService soapService, IRestRequestService resquestService,IRestSearchService searchRestSearchService,
            ISoapSearchService searchSoapService, IRestSearchServiceWrapper restSerchServiceWrapper)
        {
            if (soapService == null)
                throw new ArgumentNullException(nameof(soapService));
            if (resquestService == null)
                throw new ArgumentNullException(nameof(resquestService));
            if (searchRestSearchService == null)
                throw new ArgumentNullException(nameof(searchRestSearchService));
            if (searchSoapService == null)
                throw new ArgumentNullException(nameof(searchSoapService));
            if (restSerchServiceWrapper == null)
                throw new ArgumentNullException(nameof(searchSoapService));

            SoapRequestService = soapService;
            RestRequestService = resquestService;
            SearchRestService = searchRestSearchService;
            SearchSoapService = searchSoapService;
            RestSerchServiceWrapper = restSerchServiceWrapper;
        }
        

        // GET: Sale
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaleProduct()
        {
            return View();
        }

        public async Task<ActionResult> Authorize(SaleViewModel sale)
        {
            if (ModelState.IsValid)
            {
                ResponseViewModel responseObject;
                switch (sale.TypeSend)
                {
                    case TypeSendEnum.SOAP:
                        responseObject = await
                            SoapRequestService.AuthorizeTransaction(sale, CreateMercharOrderId());
                        break;
                    case TypeSendEnum.REST:
                        sale.MerchantOrderId = CreateMercharOrderId();
                        responseObject = await RestRequestService.AuthorizeTransaction(sale);
                        break;
                    default:
                        throw new Exception("Type send not match!");
                }

                return View("Index", responseObject);
            }

            return View("SaleProduct", sale);
            
        }

        public async Task<ActionResult> Search(ResponseViewModel sale)
        {
            var responseObject = new ResponseObject();

            switch (sale.TypeSend)
            {
                case TypeSendEnum.SOAP:
                    
                    responseObject = await SearchSoapService.Search(sale);

                    break;
                case TypeSendEnum.REST:
                    responseObject = await SearchRestService.Search(sale.PaymentId.ToString());
                    break;
                default:
                    throw  new Exception("Type send not match!");
            }

            return View("SearchSale", responseObject);
        }

        public string CreateMercharOrderId()
        {
            StringBuilder strbld = new StringBuilder(100);
            Random random = new Random();

            strbld.Append(random.Next());

            return strbld.ToString();
        }
        
    }
}

IntegracaoPagador/Views/Sale/Index.cshtml
@model IntegracaoPagador.Models.ResponseViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="row">
    @Html.ActionLink("SaleProduct", "SaleProduct")
</div>

@using (Html.BeginForm("Search", "Sale", FormMethod.Post))
{
    <div class="row">
        <fieldset>
            <div class="col-sm-6">
                @Html.LabelFor(m => m.PaymentId, "Id")
                @Html.TextBoxFor(m => m.PaymentId, new { @class="form-control"})
            </div>
        </fieldset>
        <fieldset>
            <div class="col-sm-6">
                @Html.LabelFor(m => m.TypeSend, "Type:")
                @Html.EnumDropDownListFor(m => m.TypeSend, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TypeSend)
            </div>
        </fieldset>
        
        
    </div>

    <input type="submit" value="Buscar" />
}

IntegracaoPagador/Views/Sale/SaleProduct.cshtml
@model IntegracaoPagador.Models.SaleViewModel
@{
    ViewBag.Title = "SaleProduct";
}

<h2>Authorize</h2>

@using (Html.BeginForm("Authorize", "Sale", FormMethod.Post))
{
    <div class="row">
        <fieldset>
            <legend> Customer </legend>
            @Html.LabelFor(m => m.CustomerName, "Customer Name:")
            @Html.TextBoxFor(m => m.CustomerName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CustomerName)
        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            <legend> Payment </legend>
            @Html.LabelFor(m => m.PaymentType, "Payment Type:")
            @Html.TextBoxFor(m => m.PaymentType, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PaymentType)
        
            @Html.LabelFor(m => m.PaymentAmount, "Payment Amount:")
            @Html.TextBoxFor(m => m.PaymentAmount, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PaymentAmount)

            @Html.LabelFor(m => m.PaymentProvider, "Payment Provider:")
            @Html.EnumDropDownListFor(m => m.PaymentProvider, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PaymentProvider)

            @Html.LabelFor(m => m.PaymentInstallments, "Payment Installments:")
            @Html.TextBoxFor(m => m.PaymentInstallments, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PaymentInstallments)
        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            <legend> CreditCardCar </legend>
            @Html.LabelFor(m => m.CreditCardCardNumber, "CreditCardCard Number:")
            @Html.TextBoxFor(m => m.CreditCardCardNumber, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CreditCardCardNumber)

            @Html.LabelFor(m => m.CreditCardHolder, "CreditCard Holder:")
            @Html.TextBoxFor(m => m.CreditCardHolder, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CreditCardHolder)

            @Html.LabelFor(m => m.CreditCardExpirationDate, "CreditCard ExpirationDate:")
            @Html.TextBoxFor(m => m.CreditCardExpirationDate, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CreditCardExpirationDate)

            @Html.LabelFor(m => m.CreditCardBrand, "CreditCardBrand:")
            @Html.EnumDropDownListFor(m => m.CreditCardBrand, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CreditCardBrand)

            @Html.LabelFor(m => m.CreditCardSecurityCode, "CreditCard SecurityCode:")
            @Html.TextBoxFor(m => m.CreditCardSecurityCode, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CreditCardSecurityCode)

        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            @Html.LabelFor(m => m.TypeSend, "Type:")
            @Html.EnumDropDownListFor(m => m.TypeSend, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TypeSend)
        </fieldset>
    </div>

    <input type="submit" value="Enviar" />
}

IntegracaoPagador/Views/Sale/SearchSale.cshtml
@model IntegracaoPagador.Models.ResponseObject
@{
    ViewBag.Title = "SearchSale";
}

<h2>SearchSale</h2>


@using (Html.BeginForm())
{
    <div class="row">
        <fieldset>
            <legend> Customer </legend>
            @Html.LabelFor(m => m.Customer.Name)
            @Html.TextBoxFor(m => m.Customer.Name, new { @class = "form-control" })
        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            <legend> Payment </legend>
            @Html.LabelFor(m => m.Payment.Type, "Payment Type:")
            @Html.TextBoxFor(m => m.Payment.Type, new { @class = "form-control" })
            
            @Html.LabelFor(m => m.Payment.Amount, "Payment Amount:")
            @Html.TextBoxFor(m => m.Payment.Amount, new { @class = "form-control" })
            

            @Html.LabelFor(m => m.Payment.Provider, "Payment Provider:")
            @Html.EnumDropDownListFor(m => m.Payment.Provider, new { @class = "form-control" })
            

            @Html.LabelFor(m => m.Payment.Installments, "Payment Installments:")
            @Html.TextBoxFor(m => m.Payment.Installments, new { @class = "form-control" })
            
        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            <legend> CreditCardCar </legend>
            @Html.LabelFor(m => m.Payment.CreditCard.CardNumber, "CreditCardCard Number:")
            @Html.TextBoxFor(m => m.Payment.CreditCard.CardNumber, new { @class = "form-control" })
           
            @Html.LabelFor(m => m.Payment.CreditCard.Holder, "CreditCard Holder:")
            @Html.TextBoxFor(m => m.Payment.CreditCard.Holder, new { @class = "form-control" })
            

            @Html.LabelFor(m => m.Payment.CreditCard.ExpirationDate, "CreditCard ExpirationDate:")
            @Html.TextBoxFor(m => m.Payment.CreditCard.ExpirationDate, new { @class = "form-control" })
          

            @Html.LabelFor(m => m.Payment.CreditCard.Brand, "CreditCardBrand:")
            @Html.EnumDropDownListFor(m => m.Payment.CreditCard.Brand, new { @class = "form-control" })

        </fieldset>
    </div>
}